Libary search
IsacZetterstrom/Frontend-Project pull request #29
Opened 2023-10-25 13:02 UTC by KernelTestPilot

2023-10-26 08:51 UTC, IsacZetterstrom requested changes
vite.config is not correct. double api proxy routes, and Header et.c is left from the merge?

Why is every component a Form, then rendered into a form?

2023-10-26 11:49 UTC, ledei requested changes
Glöm inte att skriva kommentarer på vad alla komponenter gör och vem som har skrivit de

2023-10-27 07:49 UTC, ledei approved these changes

2023-10-27 08:20 UTC, IsacZetterstrom approved these changes

2023-10-27 08:21 UTC, merged