Got bookingPage cognitive complexity to below 20
IsacZetterstrom/Frontend-Project pull request #64
Opened 2023-11-07 15:13 UTC by Oliver-Andersson19

put some bookingPage logic in util file

2023-11-07 17:30 UTC, ledei approved these changes

2023-11-07 17:31 UTC, ledei requested changes
add comments in utils file

2023-11-08 08:12 UTC, ledei approved these changes

2023-11-08 08:15 UTC, lollocodes approved these changes

2023-11-08 08:15 UTC, merged